koth:
  default-cap-time: 300 # in seconds

auto-koth:
  enabled: true
  delay: 20 # the amount of time after the plugin is loaded to schedule a koth
  next-delay: 300 # time between a koth being won and the next koth
  player-requirement: 0